### ISSUE TITLE
Could not load file or assembly 'Microsoft.AzureAD.Policy.Password'

### ISSUE THREAD

**Issue by tunisia-team** [synacktiv/EIPP#1]
Hello team,

Trying to execute the binary EIPP.exe, but it seems missing the library "Microsoft.AzureAD.Policy.Password.dll" to be integrated.
Executing the following command"
`EIPP.exe normalize custom_password.txt`
This is the output:
`Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AzureAD.Policy.Password, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at EIPP.Program.Normalize(String[] args)
   at EIPP.Program.Main(String[] args)`

![EIPP_Execution_Output](https://github.com/synacktiv/EIPP/assets/4363717/62a1ccb8-945a-49fb-a6f2-e6ef6c17064c)

Please help to solve the issue.

**Comment by PaulDeforge** [comment]
You need to install Microsoft's DC agent to have these DLLs.
Agent download: https://www.microsoft.com/en-us/download/details.aspx?id=57071

**The doc to read:** https://www.synacktiv.com/publications/entra-id-banned-password-lists-password-spraying-optimizations-and-defenses
**and** https://learn.microsoft.com/en-us/entra/identity/authentication/howto-password-ban-bad-on-premises-deploy

**Comment by aevy-syn** [comment]
Hi, the DLLs can indeed be extracted from an agent install. Alternatively, this particular DLL is included in the current repo at https://github.com/synacktiv/EIPP/blob/main/EIPP/EIPP/Microsoft.AzureAD.Policy.Password.dll. It must be placed in the same directory you execute the EIPP.exe tool from.
Cheers
